### ISSUE TITLE
Responses to review comments, Round 1

### ISSUE THREAD

**Issue by katyhuff** [kamuda1/dissertation#10]
I have completed the review requested in #6 (and duplicate #5). My comments appear in the pdf here (uploaded to google drive because of its size).

https://drive.google.com/open?id=1yZv1ZdPcmXk6rM29Zjgd8V99j2aeW-hx

This issue can be closed when a PR is merged which handles the comments in this pdf.

**Comment by kamuda1** [comment]
@katyhuff Here's my work in progress edits. I've added multiple figures, fixed formatting issues, and added content to address comments throughout. Steps left include:
- Incorporate more theory sections into thesis
- Fix Chapter 4 'trained in' nonsense
- Describe heavy/medium/light better in section 4.2.6.2
- Add comparison with Jacobs work (spoiler, we get a better F1 score. Woohoo!)

[kamuda_dissertation_wip_edits.pdf](https://github.com/kamuda1/kamuda-2019-dissertation/files/3665187/kamuda_dissertation_wip_edits.pdf)

**Comment by katyhuff** [comment]
Great! I have this on my calendar for today, but if it's not quite complete, maybe I should hold off on reading it until it's really final. Let me know when all of those things are complete?

**Comment by kamuda1** [comment]
@katyhuff Here's the updated draft with comments addressed: [kamuda_dissertation_updated.pdf](https://github.com/kamuda1/kamuda-2019-dissertation/files/3692072/kamuda_dissertation_updated.pdf)

**Comment by katyhuff** [comment]
Thanks! Will get this back to you ASAP (probably monday or tuesday).

**Comment by katyhuff** [comment]
Final comments attached: 
[kamuda_dissertation-round2.pdf](https://github.com/kamuda1/kamuda-2019-dissertation/files/3722623/kamuda_dissertation-round2.pdf)
