### ISSUE TITLE
Huff Review Comments

### ISSUE THREAD

**Issue by katyhuff** [kamuda1/dissertation#2]
Some review comments are attached below (mostly covering the first two chapters in detail, with some scattered comments in later chapters). This issue can be closed when the comments in the pdf have been handled.

[Kamuda_Dissertation_updated.pdf](https://github.com/kamuda1/kamuda-2019-dissertation/files/3296995/Kamuda_Dissertation_updated.pdf)

**Comment by katyhuff** [comment]
@kamuda1

**Comment by kamuda1** [comment]
On fig 2.11, the x-axis is absolute temperature. The mathematical definition of the y-axis is the percent change in peak position relative to the peak's location at room temperature.

Lets say a 662 keV peak was located at channel 200 when measured at room temperature. At 35 C the same peak is measured at channel 190. This corresponds to a relative peak position of 0.95 at 35 C.

**Comment by kamuda1** [comment]
Comments and edits have been addressed.
