### ISSUE TITLE
Review dissertation draft

### ISSUE THREAD

**Issue by kamuda1** [kamuda1/dissertation#6]
@katyhuff Requesting a review of the first complete draft of the dissertation. Might be able to merge this with Issue #5.

[Kamuda_Dissertation_draft_1.pdf](https://github.com/kamuda1/kamuda-2019-dissertation/files/3581291/Kamuda_Dissertation_draft_1.pdf)

**Comment by katyhuff** [comment]
Excellent! Will aim to read through this weekend!

**Comment by katyhuff** [comment]
Closed with #10
